[build]
# 병렬 빌드 작업 수 설정 (CPU 코어 수에 맞게 조정)
jobs = 4

[target.x86_64-pc-windows-msvc]
# Windows에서 링커 최적화
rustflags = ["-C", "target-cpu=native", "-C", "link-arg=-Wl,--no-as-needed"]

[target.aarch64-apple-darwin]
# macOS에서 링커 최적화
rustflags = ["-C", "target-cpu=native"]

[target.x86_64-apple-darwin]
# Intel Mac에서 링커 최적화
rustflags = ["-C", "target-cpu=native"]

# 의존성 컴파일 최적화
[profile.dev]
# 개발 빌드에서도 일부 최적화 적용
opt-level = 1
debug = true
split-debuginfo = "unpacked"

[profile.release]
# 릴리즈 빌드 최적화
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true
